/**
 * My Learning Bio — the calls, on the LMS's axios client. Every call answers
 * the full bio object the server builds (see server src/learningbio/index.js).
 */
import client from '../utils/api';
import saveToDrive from '../integrations/google/saveToDrive';

const unwrap = (err) => {
    const body = err.response?.data;
    const e = new Error(body?.message || body?.error || (!err.response ? 'You appear to be offline.' : 'Something went wrong.'));
    e.code = body?.code || (err.response?.status === 401 ? 'SESSION_EXPIRED' : !err.response ? 'OFFLINE' : 'ERROR');
    e.status = err.response?.status;
    throw e;
};
const get = (p) => client.get(`/learning-bio${p}`).then((r) => r.data).catch(unwrap);
const post = (p, b) => client.post(`/learning-bio${p}`, b).then((r) => r.data).catch(unwrap);
const put = (p, b) => client.put(`/learning-bio${p}`, b).then((r) => r.data).catch(unwrap);

export const bioApi = {
    full: () => get(''),
    summary: () => get('/summary'),
    regenerate: () => post('/regenerate'),
    refresh: () => post('/refresh'),
    saveBio: (body) => put('/bio', body),
    interests: (body) => put('/interests', body),
    settings: (body) => put('/settings', body),
    /** The bio as a PDF, handed to the browser as a download. */
    downloadPdf: async (name = 'Learning_Bio') => {
        const res = await client.get('/learning-bio/pdf', { responseType: 'blob' }).catch(unwrap);
        const url = URL.createObjectURL(res.data);
        const fileName = `${String(name).replace(/[^A-Za-z0-9]+/g, '_')}_Learning_Bio.pdf`;
        const a = document.createElement('a');
        a.href = url;
        a.download = fileName;
        document.body.appendChild(a);
        a.click();
        a.remove();
        setTimeout(() => URL.revokeObjectURL(url), 1000);

        // A copy in the student's own Drive, when they have connected one.
        // Deliberately not awaited: the download has already happened.
        saveToDrive(res.data, {
            name: fileName,
            description: 'Your learning bio, generated by YATICORP.',
            reason: 'So your learning bio is kept in your own Google Drive.'
        });
    }
};

export const STATUS_TONE = {
    Learning: { bar: 'from-slate-400 to-slate-500', chip: 'bg-slate-100 text-slate-700' },
    Developing: { bar: 'from-sky-400 to-indigo-500', chip: 'bg-sky-100 text-sky-800' },
    Proficient: { bar: 'from-indigo-500 to-violet-500', chip: 'bg-indigo-100 text-indigo-800' },
    Advanced: { bar: 'from-emerald-500 to-teal-500', chip: 'bg-emerald-100 text-emerald-800' }
};

export const fmtDate = (d) => (d ? new Date(d).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }) : '');
