/** Shared pieces for the verification screens, styled after the Jobs cards and the login page's buttons. */
import { AlertCircle, ArrowRight, CheckCircle2, Loader2, WifiOff, LogIn, FlaskConical } from 'lucide-react';
import { Link } from 'react-router-dom';
export const Card = ({ children, className = '' }) => (<div className={`relative overflow-hidden rounded-3xl border border-indigo-100 bg-white p-6 shadow-sm sm:p-8 ${className}`}><span aria-hidden="true" className="pointer-events-none absolute -right-16 -top-16 h-48 w-48 rounded-full bg-indigo-100/70 blur-2xl" /><div className="relative">{children}</div></div>);
export const Heading = ({ icon: Icon, title, children }) => (<div className="mb-6 flex items-start gap-4"><span className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-indigo-600 text-white shadow-lg shadow-indigo-200"><Icon size={24} /></span><div className="min-w-0"><h2 className="text-xl font-extrabold text-slate-900">{title}</h2>{children && <p className="mt-1 text-sm text-slate-500">{children}</p>}</div></div>);
export const PrimaryButton = ({ children, loading, loadingText, icon: Icon = ArrowRight, className = '', ...rest }) => (<button type="button" {...rest} disabled={rest.disabled || loading} className={`group relative flex w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-indigo-600 to-violet-600 px-4 py-3.5 text-base font-bold text-white shadow-lg shadow-indigo-500/25 transition-all hover:from-indigo-700 hover:to-violet-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50 ${className}`}>{loading ? <Loader2 size={18} className="animate-spin" /> : null}{loading && loadingText ? loadingText : children}{!loading && Icon && <Icon size={18} className="transition-transform group-hover:translate-x-0.5" />}</button>);
export const SecondaryButton = ({ children, icon: Icon, className = '', ...rest }) => (<button type="button" {...rest} className={`inline-flex items-center justify-center gap-1.5 rounded-xl border border-indigo-200 bg-white px-4 py-2.5 text-sm font-bold text-indigo-600 transition-colors hover:bg-indigo-50 disabled:cursor-not-allowed disabled:opacity-60 ${className}`}>{Icon && <Icon size={15} />}{children}</button>);
export const ErrorNotice = ({ error, onRetry }) => { if (!error) return null; const Icon = error.code === 'OFFLINE' ? WifiOff : error.code === 'SESSION_EXPIRED' ? LogIn : AlertCircle; return (<div role="alert" className="mt-4 flex items-start gap-3 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800 animate-fade-in"><Icon size={17} className="mt-0.5 shrink-0" /><div className="min-w-0 flex-1"><p className="font-semibold">{error.message}</p>{error.code === 'SESSION_EXPIRED' && <Link to="/login" className="mt-1 inline-block text-xs font-bold underline">Sign in again</Link>}{error.code !== 'SESSION_EXPIRED' && onRetry && <button type="button" onClick={onRetry} className="mt-1 text-xs font-bold underline">Try again</button>}</div></div>); };
export const Reassurance = ({ items }) => (<ul className="mt-5 space-y-1.5 text-sm text-slate-600">{items.map((t) => <li key={t} className="flex items-center gap-2"><CheckCircle2 size={15} className="shrink-0 text-emerald-500" /> {t}</li>)}</ul>);
export const SuccessMark = ({ label }) => (<div className="flex flex-col items-center text-center"><span className="animate-pop-in flex h-20 w-20 items-center justify-center rounded-full bg-emerald-100 ring-8 ring-emerald-50"><span className="flex h-14 w-14 items-center justify-center rounded-full bg-emerald-500 text-white shadow-lg shadow-emerald-200"><CheckCircle2 size={32} strokeWidth={2.5} /></span></span>{label && <p className="mt-4 text-xl font-extrabold text-slate-900">{label}</p>}</div>);
export const MockNotice = ({ children }) => (<div className="mt-5 flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-xs text-amber-900"><FlaskConical size={16} className="mt-0.5 shrink-0" /><div><p className="font-bold uppercase tracking-wider">Development mode</p><p className="mt-0.5">{children}</p></div></div>);
